### ISSUE TITLE
Can't build on Electron ^33.0.2. No module named 'distutils'

### ISSUE THREAD

**Issue by JerryI** [davidcann/electron-trackpad-utils#3]
It complains about missing package 

```bash
Traceback (most recent call last):
npm error   File "/Users/kirill/Github/wolfram-js-frontend/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
npm error     import gyp  # noqa: E402
npm error     ^^^^^^^^^^
npm error   File "/Users/kirill/Github/wolfram-js-frontend/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
npm error     import gyp.input
npm error   File "/Users/kirill/Github/wolfram-js-frontend/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
npm error     from distutils.version import StrictVersion
npm error ModuleNotFoundError: No module named 'distutils'
```

There is a fix for that

```
brew install python-setuptools
```

it will bring the missing tool and then it works normally.

**Comment by davidcann** [comment]
Thanks for the report. I'm not sure if there's a better way, but I added this to `package.json`:

```
"scripts": {
	"preinstall": "python3 -m pip show setuptools || python3 -m pip install --user setuptools",
	"install": "node-gyp rebuild"
},
```

**Comment by JerryI** [comment]
> Thanks for the report. I'm not sure if there's a better way, but I added this to `package.json`:
> 
> 
> 
> ```
> 
> "scripts": {
> 
> 	"preinstall": "python3 -m pip show setuptools || python3 -m pip install --user setuptools",
> 
> 	"install": "node-gyp rebuild"
> 
> },
> 
> ```

Thank you for those nice addons. It makes electron app feel much more natural on mac.
